##############################
# Application
##############################
spring.application.name=sudolife

##############################
# Persistence
##############################
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

##############################
# Security
##############################
api.security.token.secret=${API_SECURITY_TOKEN_SECRET:local-development-token-secret}
api.security.token.issuer=${API_SECURITY_TOKEN_ISSUER:sudolife-api}
api.security.token.expiration-minutes=${API_SECURITY_TOKEN_EXPIRATION_MINUTES:120}

##############################
# Documentation
##############################
springdoc.swagger-ui.path=/swagger.html
