##############################
# Application
##############################
app.version=1.0.1
spring.application.name=sudolife

##############################
# Persistence
##############################
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

##############################
# Security
##############################
api.security.token.secret=${API_SECURITY_TOKEN_SECRET:local-development-token-secret}
api.security.token.issuer=${API_SECURITY_TOKEN_ISSUER:sudolife-api}
api.security.token.expiration-minutes=${API_SECURITY_TOKEN_EXPIRATION_MINUTES:120}

##############################
# Strava
##############################
   ## URLs ##
strava.authorization-url=${STRAVA_AUTHORIZATION_URL:https://www.strava.com/oauth/authorize}
strava.token-url=${STRAVA_TOKEN_URL:https://www.strava.com/api/v3/oauth/token}
strava.deauthorization-url=${STRAVA_DEAUTHORIZATION_URL:https://www.strava.com/oauth/deauthorize}
strava.activities-url=${STRAVA_ACTIVITIES_URL:https://www.strava.com/api/v3/athlete/activities}
strava.activity-detail-url=${STRAVA_ACTIVITY_DETAIL_URL:https://www.strava.com/api/v3/activities/{activityId}}
strava.activity-streams-url=${STRAVA_ACTIVITY_STREAMS_URL:https://www.strava.com/api/v3/activities/{activityId}/streams}
   ## KEYs ##
strava.client-id=${STRAVA_CLIENT_ID:258948}
strava.client-secret=${STRAVA_CLIENT_SECRET:5f6926849e52ce734dfd2f5f5e4265ea27733c96}
   ## INTERVALS ##
strava.connect-timeout=${STRAVA_CONNECT_TIMEOUT:2s}
strava.read-timeout=${STRAVA_READ_TIMEOUT:5s}
strava.summary-sync.polling-interval=${STRAVA_SUMMARY_SYNC_POLLING_INTERVAL:PT24H}
strava.summary-sync.worker-interval=${STRAVA_SUMMARY_SYNC_WORKER_INTERVAL:PT1M}
strava.summary-sync.retry-backoff=${STRAVA_SUMMARY_SYNC_RETRY_BACKOFF:PT15M}
strava.summary-sync.max-attempts=${STRAVA_SUMMARY_SYNC_MAX_ATTEMPTS:3}
strava.summary-sync.scheduling-enabled=${STRAVA_SUMMARY_SYNC_SCHEDULING_ENABLED:true}
strava.stream-sync.worker-interval=${STRAVA_STREAM_SYNC_WORKER_INTERVAL:PT1M}
strava.stream-sync.retry-backoff=${STRAVA_STREAM_SYNC_RETRY_BACKOFF:PT15M}
strava.stream-sync.max-attempts=${STRAVA_STREAM_SYNC_MAX_ATTEMPTS:3}
strava.stream-sync.scheduling-enabled=${STRAVA_STREAM_SYNC_SCHEDULING_ENABLED:true}

######### Strava Frontend URLs ###########
strava.redirect-uri=${STRAVA_REDIRECT_URI:https://tori-unsized-amari.ngrok-free.dev/api/strava/callback}
strava.frontend-success-redirect-url=${STRAVA_FRONTEND_SUCCESS_REDIRECT_URL:http://localhost:3000/settings/connections/strava/success}
strava.frontend-failure-redirect-url=${STRAVA_FRONTEND_FAILURE_REDIRECT_URL:http://localhost:3000/settings/connections/strava/failure}

##############################
# Documentation
##############################
springdoc.swagger-ui.path=/swagger.html
