package com.sudolife.application.service.ratelimit;

public enum RateLimitPolicy {

    LOGIN_IP,
    LOGIN_EMAIL,
    LOGIN_EMAIL_ORIGIN,
    REGISTRATION_ORIGIN,
    REGISTRATION_EMAIL,
    PASSWORD_RECOVERY_START_ORIGIN,
    PASSWORD_RECOVERY_START_EMAIL,
    PASSWORD_RECOVERY_COMPLETE_ORIGIN,
    GENERIC_API
}
