create table training_profiles (
    id bigint generated by default as identity primary key,
    user_email varchar(255) not null,
    birth_year integer not null,
    constraint uk_training_profiles_user_email unique (user_email)
);
