create table coaching_profiles (
    id bigint generated by default as identity primary key,
    user_email varchar(255) not null,
    target_distance_kilometers double precision not null,
    target_pace_seconds_per_kilometer integer,
    target_date date,
    readiness varchar(32) not null,
    injury_concern boolean not null,
    constraint uk_coaching_profiles_user_email unique (user_email)
);
