create table users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    constraint uk_users_email unique (email)
);
