create table strava_data_consent_records (
    id bigint generated by default as identity primary key,
    user_email varchar(255) not null,
    purpose varchar(64) not null,
    consent_version varchar(128) not null,
    language varchar(16) not null,
    consented_at timestamp with time zone not null,
    source varchar(64) not null,
    constraint uk_strava_data_consent_records_user_purpose_version unique (user_email, purpose, consent_version)
);

create index ix_strava_data_consent_records_user_email on strava_data_consent_records(user_email);
