create table password_recovery_tokens (
    id bigint generated by default as identity primary key,
    user_email varchar(255) not null,
    token_hash varchar(64) not null,
    expires_at timestamp with time zone not null,
    used_at timestamp with time zone,
    created_at timestamp with time zone not null,
    constraint fk_password_recovery_tokens_user_email foreign key (user_email) references users(email),
    constraint uk_password_recovery_tokens_token_hash unique (token_hash)
);

create index idx_password_recovery_tokens_user_email_active
    on password_recovery_tokens (user_email, used_at, expires_at);
