create table strava_account_links (
    id bigint generated by default as identity primary key,
    user_email varchar(255) not null,
    athlete_id bigint not null,
    active_athlete_id bigint,
    access_token varchar(2048),
    refresh_token varchar(2048),
    expires_at timestamp with time zone,
    active boolean not null,
    linked_at timestamp with time zone not null,
    unlinked_at timestamp with time zone,
    constraint ck_strava_account_links_active_authorization check (
        (active = true and active_athlete_id = athlete_id and access_token is not null and refresh_token is not null and expires_at is not null and unlinked_at is null)
        or
        (active = false and active_athlete_id is null and access_token is null and refresh_token is null and expires_at is null and unlinked_at is not null)
    )
);

create unique index uk_strava_account_links_active_athlete_id on strava_account_links(active_athlete_id);

create index ix_strava_account_links_user_email_active on strava_account_links(user_email, active);

create index ix_strava_account_links_athlete_id_active on strava_account_links(athlete_id, active);

create table strava_authorization_states (
    state varchar(255) primary key,
    user_email varchar(255) not null,
    expires_at timestamp with time zone not null,
    consumed_at timestamp with time zone
);

create index ix_strava_authorization_states_user_email on strava_authorization_states(user_email);
