create table strava_activity_detail_snapshots (
    id bigint generated by default as identity primary key,
    activity_summary_id bigint not null,
    user_email varchar(255) not null,
    source_activity_id bigint not null,
    activity_type varchar(50) not null,
    raw_sport_type varchar(255) not null,
    name varchar(255) not null,
    start_date timestamp with time zone not null,
    distance_meters double precision,
    moving_time_seconds integer,
    average_speed_meters_per_second double precision,
    pace_seconds_per_kilometer double precision,
    total_elevation_gain_meters double precision,
    max_speed_meters_per_second double precision,
    average_heart_rate double precision,
    max_heart_rate double precision,
    average_cadence double precision,
    average_watts double precision,
    calories double precision,
    fetched_at timestamp with time zone not null,
    constraint fk_strava_activity_detail_snapshots_summary foreign key (activity_summary_id) references strava_activity_summaries(id),
    constraint uk_strava_activity_detail_snapshots_summary unique (activity_summary_id)
);

create index ix_strava_activity_detail_snapshots_user_source
    on strava_activity_detail_snapshots(user_email, source_activity_id);
