create table strava_activity_stream_snapshots (
    id bigint generated by default as identity primary key,
    activity_summary_id bigint not null,
    account_link_id bigint not null,
    user_email varchar(255) not null,
    source_activity_id bigint not null,
    available_metric_names varchar(512) not null,
    stream_samples_json text not null,
    fetched_at timestamp with time zone not null,
    constraint fk_strava_activity_stream_snapshots_summary foreign key (activity_summary_id) references strava_activity_summaries(id),
    constraint uk_strava_activity_stream_snapshots_summary unique (activity_summary_id)
);

create index ix_strava_activity_stream_snapshots_account_link
    on strava_activity_stream_snapshots(account_link_id);

create index ix_strava_activity_stream_snapshots_user_source
    on strava_activity_stream_snapshots(user_email, source_activity_id);
