create table strava_activity_stream_sync_jobs (
    id bigint generated by default as identity primary key,
    activity_summary_id bigint not null,
    open_activity_summary_id bigint,
    account_link_id bigint not null,
    user_email varchar(255) not null,
    source_activity_id bigint not null,
    priority varchar(32) not null,
    status varchar(32) not null,
    attempt_count integer not null,
    run_after timestamp with time zone not null,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    failure_reason varchar(64),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_strava_activity_stream_sync_jobs_summary foreign key (activity_summary_id) references strava_activity_summaries(id),
    constraint uk_strava_activity_stream_sync_jobs_open_summary unique (open_activity_summary_id)
);

create index ix_strava_activity_stream_sync_jobs_runnable
    on strava_activity_stream_sync_jobs(status, run_after, priority, created_at);

create index ix_strava_activity_stream_sync_jobs_account_link
    on strava_activity_stream_sync_jobs(account_link_id);
